### ISSUE TITLE
Preprocessing of images for each model.

### ISSUE THREAD

**Issue by OsvaVelarde** [nyukat/mammography_metarepository#12]
Dear,
First, congratulations and thank you for this repository of models. I´m trying to evaluate the models in the CBIS-DDSM database.
I can execute the codes without problem but a query about the models. Does each docker apply ALL the preprocessing that the images need for each model? In case yes, I should only put the raw images in the corresponding folder, right?

In particular, I have doubts about the orientations and the normalization of the images.

1. [The paper of  **end2end network**](https://arxiv.org/pdf/1708.09427.pdf) does not specify whether image orientation is important. Therefore, HORIZONTAL_FLIP would not affect performance. Is it OK?
Also, the authors claim that there is no preprocessing (except subtracting the average). Are artifacts like white text/labels not removed from images? I´m trying to reproduce the results with CBIS-DDSM and I get AUC = 0.7 (disagrees with the results presented in the paper). Perhaps there is some detail that I forget.

2. For the **nyu-model network:** is there any standardization of the images? [In the original paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8861376), there is no information about this. Normalization isn´t mentioned in the NYU dataset report, but I'm in doubt.  The heatmaps generated by the network do not seem reliable to me as they indicate probability equal to 1 in almost the entire breast area. Perhaps this is due to the lack of normalization or perhaps the distribution of CBIS-DDSM is very different from the NYU database. 

Maybe I should write to the authors separately but if you have information about it, I will appreciate it.

Thanks!
Osvaldo

**Comment by jwitos** [comment]
Hi Osvaldo, thank you for your comments.

> Does each docker apply ALL the preprocessing that the images need for each model?

Yes, each docker container applies all necessary preprocessing required by each of the models.

> In case yes, I should only put the raw images in the corresponding folder, right?

Yes, you only need to have raw images and scripts will take care of all preprocessing.
However, please note that all included models expect the images to be 16-bit PNGs. Script for DICOM to 16-bit PNG conversion is in our README. Also, if you are using a custom dataset, you can additionally make sure that your images are presentation-intent, i.e. all necessary grayscale conversions have been applied (see Usage Notes: Images on page 11 of our preprint for details).

>In particular, I have doubts about the orientations and the normalization of the images.
The paper of end2end network does not specify whether image orientation is important. Therefore, HORIZONTAL_FLIP would not affect performance. Is it OK?

Yes, you should be safe to have `horizontal_flip` set to `NO`. Actually, in almost all scenarios `NO` is a safe option, unless you know that the images are mis-oriented. This parameter is really just an artifact from the NYU Dataset and you don't have to worry about it.

>Also, the authors claim that there is no preprocessing (except subtracting the average). Are artifacts like white text/labels not removed from images? I´m trying to reproduce the results with CBIS-DDSM and I get AUC = 0.7 (disagrees with the results presented in the paper). Perhaps there is some detail that I forget.

When you say you are trying to reproduce the results, are you using the meta-repository or are you trying to reproduce the results yourself?
Two comments _if you are using the meta-repository_:
1. Are you using a full CBIS-DDSM dataset or just a part of it? As described in our paper, we evaluate models only on a subset of 188 exams, as defined by Shen et al. paper. Please refer to our appendix, specifically page 11 and Supplementary Table 1 (page 15) to see which studies we used for evaluation.
2. Did you change the mean pixel value of the dataset? End2end model expects that you provide a mean pixel intensity parameter. To do that you need to change models/end2end/config.txt file line 5. By default, the value is 44.4 (INbreast mean pixel value), but for DDSM we used a 52.18 mean pixel value.
The only preprocessing we do on the end2end model is [downsizing to 1152x896](https://github.com/nyukat/mammography_metarepository/blob/b2ae73764fd9bb5606f9205b70b39d186527d723/models/end2end/predict/preprocess.py#L30), as described in Section 3.1.1 of the end2end paper.

> For the nyu-model network: is there any standardization of the images? In the original paper, there is no information about this. Normalization isn´t mentioned in the NYU dataset report, but I'm in doubt. 

You do not have to perform any standardization of your images prior to running the script. The standardization is done automatically, e.g. [here](https://github.com/nyukat/breast_cancer_classifier/blob/master/src/data_loading/loading.py#L44).

> The heatmaps generated by the network do not seem reliable to me as they indicate probability equal to 1 in almost the entire breast area. Perhaps this is due to the lack of normalization or perhaps the distribution of CBIS-DDSM is very different from the NYU database.

This is likely due to the difference in distribution between the CBIS-DDSM data set and the NYU data set. The images in the CBIS-DDSM dataset are scanned films rather than digital mammograms. Note that in our paper we showed that the models trained on the CBIS-DDSM dataset don’t generalize well to the NYU data set, so if the heatmaps don’t point to anything meaningful it is not surprising.

**Comment by OsvaVelarde** [comment]
Thank you for your answers! I was already able to reproduce the results with the 188 exams.

One more question: Do you remember what Shen's criteria were for defining those 188 exams? Reading the paper again, I can't find the criteria.

Osvaldo

**Comment by jwitos** [comment]
@OsvaVelarde Sorry, I unfortunately do not know the criteria. We obtained the list of those 188 studies directly from Li Shen by contacting him.
